# Generated by Django 5.2.15 on 2026-07-23 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DocumentOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('document.created', 'Created'), ('document.content_replaced', 'Content Replaced'), ('document.metadata_updated', 'Metadata Updated'), ('document.deleted', 'Deleted')], max_length=64)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('document_id', models.UUIDField()),
                ('content_revision', models.PositiveIntegerField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('dispatched', 'Dispatched'), ('dead_letter', 'Dead Letter')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='doc_outbox_due_idx'), models.Index(fields=['status', 'claim_expires_at'], name='doc_outbox_lease_idx'), models.Index(fields=['document_id', 'content_revision'], name='doc_outbox_revision_idx'), models.Index(fields=['occurred_at'], name='doc_outbox_time_idx')],
            },
        ),
    ]
